import os
import shutil
from pathlib import Path

def main():
    base = Path("c:/Users/Guntass Kaur/New folder (19)/boi/backend/app")
    
    # 1. Create Directories
    dirs_to_create = [
        "api/auth", "api/transactions", "api/fraud", "api/graph", "api/reports", "api/websocket",
        "database", "models"
    ]
    for d in dirs_to_create:
        (base / d).mkdir(parents=True, exist_ok=True)

    # 2. Move Database files
    if (base / "core/database.py").exists():
        shutil.move(str(base / "core/database.py"), str(base / "database/postgres.py"))
    if (base / "models/all_models.py").exists():
        shutil.move(str(base / "models/all_models.py"), str(base / "database/schema.py"))

    # 3. Move API Routes
    route_mappings = {
        "api/routes/auth.py": "api/auth/router.py",
        "api/routes/transactions.py": "api/transactions/router.py",
        "api/routes/fraud.py": "api/fraud/router.py",
        "api/routes/graph.py": "api/graph/router.py",
        "api/routes/compliance.py": "api/reports/router.py",
        "api/routes/ws.py": "api/websocket/router.py"
    }
    for src, dst in route_mappings.items():
        if (base / src).exists():
            shutil.move(str(base / src), str(base / dst))

    # 4. Move Services
    service_mappings = {
        "ml/dataset_loader.py": "services/dataset_loader.py",
        "ml/graph_builder.py": "services/graph_engine.py",
        "services/fraud_scoring.py": "services/fraud_engine.py",
    }
    for src, dst in service_mappings.items():
        if (base / src).exists():
            shutil.move(str(base / src), str(base / dst))

    # 5. Create empty stubs for new services
    stubs = ["services/feature_engineering.py", "services/shap_engine.py", "services/report_engine.py"]
    for stub in stubs:
        with open(base / stub, "w") as f:
            f.write("# Stub generated by refactor\n")

    # 6. Global Search and Replace for imports
    def replace_in_file(filepath, replacements):
        try:
            with open(filepath, "r") as f:
                content = f.read()
            for old, new in replacements.items():
                content = content.replace(old, new)
            with open(filepath, "w") as f:
                f.write(content)
        except Exception as e:
            print(f"Error replacing in {filepath}: {e}")

    replacements = {
        "from app.core.database import Base": "from app.database.postgres import Base",
        "from app.core.database import get_db": "from app.database.postgres import get_db",
        "from app.core.database import engine": "from app.database.postgres import engine",
        "from app.models.all_models import": "from app.database.schema import",
        "import app.models.all_models": "import app.database.schema",
        "from app.models import": "from app.database.schema import",
        "import app.models": "import app.database.schema",
        "app.ml.dataset_loader": "app.services.dataset_loader",
        "app.ml.graph_builder": "app.services.graph_engine",
        "app.services.fraud_scoring": "app.services.fraud_engine",
        "from app.api.routes import": "# from app.api.routes import" # Needs manual fix in main.py
    }

    for ext in ["*.py"]:
        for filepath in base.rglob(ext):
            replace_in_file(filepath, replacements)
            
    print("Refactor script complete.")

if __name__ == "__main__":
    main()
